### ISSUE TITLE
Runtime error when using multi-gpu training

### ISSUE THREAD

**Issue by lihui52** [ymhzyj/UMMAFormer#17]
I try to use multi-gpus to train the model, I set devices: [0,1] in config file, but it doesn't work: 
[Train]: Epoch 0 started
Traceback (most recent call last):
  File "UMMAFormer-main/train.py", line 244, in <module>
    main(args)
  File "UMMAFormer-main/train.py", line 180, in main
    train_one_epoch(
  File "UMMAFormer-main/libs/utils/train_utils.py", line 299, in train_one_epoch
    losses = model(video_list)
  File "UMMAFormer-main/envs/deepfake11/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "UMMAFormer-main/envs/deepfake11/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 154, in forward
    raise RuntimeError("module must have its parameters and buffers "
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

**Comment by ghost** [comment]
same

**Comment by ghost** [comment]
How to solve it
